use std::fs;
use std::path::Path;

use anyhow::Result;
use base64::engine::general_purpose::STANDARD;
use base64::Engine;

use crate::model::{CaseResult, Classification, RunReport};

pub fn render_html(report: &RunReport, root: &Path) -> Result<String> {
    let rows = report.results.iter().map(render_row).collect::<String>();
    let failures = report
        .results
        .iter()
        .filter(|result| result.classification != Classification::Passed)
        .map(|result| render_detail(result, root))
        .collect::<Result<String>>()?;
    let embedded_json = escape_script(&serde_json::to_string(report)?);
    Ok(format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>DeepLink Lab · {run_id}</title>
<style>
:root{{--ink:#102033;--muted:#667085;--line:#d9e0e8;--panel:#fff;--page:#f4f7fb;--blue:#1769e0;--green:#087443;--red:#bb2333;--amber:#9a6700;--shadow:0 12px 32px rgba(16,32,51,.08)}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--page);color:var(--ink);font:15px/1.55 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}main{{width:min(1240px,calc(100% - 32px));margin:36px auto 72px}}header{{display:grid;grid-template-columns:1fr auto;gap:24px;align-items:end;margin-bottom:24px}}h1{{margin:0;font-size:clamp(28px,5vw,48px);letter-spacing:-.04em}}h2{{font-size:22px;margin:34px 0 12px}}.eyebrow{{color:var(--blue);font-weight:750;text-transform:uppercase;letter-spacing:.12em;font-size:12px}}.muted{{color:var(--muted)}}.scope{{max-width:700px;margin-top:8px}}.cards{{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}}.card,.panel,.case{{background:var(--panel);border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow)}}.card{{padding:16px}}.card b{{display:block;font-size:28px;letter-spacing:-.03em}}.panel{{overflow:auto}}table{{border-collapse:collapse;width:100%;min-width:980px}}th,td{{padding:12px 14px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;background:color-mix(in srgb,var(--panel),var(--page) 35%);position:sticky;top:0}}tr:last-child td{{border-bottom:0}}code{{font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;background:color-mix(in srgb,var(--panel),var(--blue) 7%);padding:2px 5px;border-radius:5px}}.status{{display:inline-flex;border-radius:999px;padding:3px 9px;font-weight:750;font-size:12px}}.passed{{color:var(--green);background:#e8f7ef}}.failed{{color:var(--red);background:#fdecef}}.unavailable{{color:var(--amber);background:#fff4d6}}.case{{padding:18px;margin:12px 0;display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,420px);gap:18px}}.case h3{{margin:0 0 10px}}.facts{{display:grid;grid-template-columns:130px 1fr;gap:7px 12px}}.facts dt{{color:var(--muted)}}.facts dd{{margin:0;overflow-wrap:anywhere}}img{{display:block;width:100%;border-radius:10px;border:1px solid var(--line);background:#111}}details{{margin-top:12px}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#101828;color:#e6edf5;border-radius:10px;padding:12px;max-height:300px;overflow:auto;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}}footer{{margin-top:38px;color:var(--muted);font-size:13px}}@media(max-width:850px){{.cards{{grid-template-columns:repeat(2,1fr)}}header{{grid-template-columns:1fr}}.case{{grid-template-columns:1fr}}}}@media(prefers-color-scheme:dark){{:root{{--ink:#e8eef7;--muted:#9aa8bb;--line:#334155;--panel:#142033;--page:#0b1220;--blue:#65a4ff;--shadow:none}}.passed{{background:#123e2c}}.failed{{background:#4b1f2a}}.unavailable{{background:#443713}}}}
</style>
</head>
<body><main>
<header><div><div class="eyebrow">Local simulated runtime evidence</div><h1>DeepLink Lab</h1><p class="scope muted">Static validation and local Simulator/emulator observations are separate evidence layers. This report does not certify physical-device, store-attribution, or authenticated consumer-app behavior.</p></div><div class="muted"><b>{run_id}</b><br>{generated}</div></header>
<section class="cards"><div class="card"><span class="muted">Cases</span><b>{total}</b></div><div class="card"><span class="muted">Passed</span><b>{passed}</b></div><div class="card"><span class="muted">Failed</span><b>{failed}</b></div><div class="card"><span class="muted">Unavailable</span><b>{unavailable}</b></div><div class="card"><span class="muted">Duration</span><b>{duration:.2}s</b></div></section>
<h2>Evidence matrix</h2><div class="panel"><table><thead><tr><th>Case</th><th>Platform</th><th>Start</th><th>Source</th><th>Expected</th><th>Actual</th><th>Classification</th><th>Duration</th><th>Replay</th></tr></thead><tbody>{rows}</tbody></table></div>
<h2>Failures and unavailable observations</h2>{failure_block}
<footer>Generated by DeepLink Lab {version}. Screenshot pixels, logs, commands, hashes, starting state, and replay live in the run directory. Simulator/emulator evidence is not real-device proof.</footer>
<script type="application/json" id="deeplink-lab-report">{embedded_json}</script>
</main></body></html>"#,
        run_id = h(&report.run_id),
        generated = h(&report.generated_at.to_rfc3339()),
        total = report.summary.total,
        passed = report.summary.passed,
        failed = report.summary.failed,
        unavailable = report.summary.unavailable,
        duration = report.summary.duration_ms as f64 / 1000.0,
        rows = rows,
        failure_block = if failures.is_empty() {
            "<p class=\"muted\">No failures or unavailable observations.</p>".to_owned()
        } else {
            failures
        },
        version = h(&report.tool_version),
        embedded_json = embedded_json,
    ))
}

fn render_row(result: &CaseResult) -> String {
    let class = status_class(result.classification);
    format!(
        "<tr><td><b>{}</b><br><span class=\"muted\">repeat {}</span></td><td>{}</td><td><code>{:?}/{:?}</code></td><td><code>{:?}</code></td><td>{}</td><td>{}</td><td><span class=\"status {}\">{:?}</span></td><td>{}ms</td><td><code>{}</code></td></tr>",
        h(&result.case_id), result.repeat, result.platform, result.starting_state.install,
        result.starting_state.launch, result.source.context, destination(&result.expected),
        destination(&result.actual), class, result.classification, result.duration_ms, h(&result.replay)
    )
}

fn render_detail(result: &CaseResult, root: &Path) -> Result<String> {
    let image = result.evidence.screenshot.as_ref().and_then(|relative| {
        let path = root.join(relative);
        fs::read(&path).ok().map(|bytes| {
            let mime = if path.extension().and_then(|value| value.to_str()) == Some("jpg") {
                "image/jpeg"
            } else {
                "image/png"
            };
            format!("data:{mime};base64,{}", STANDARD.encode(bytes))
        })
    });
    let logs = fs::read_to_string(root.join(&result.evidence.logs))
        .unwrap_or_else(|_| "Log file unavailable".to_owned());
    let image = image
        .map(|uri| {
            format!(
                "<img alt=\"Screenshot for {}\" src=\"{}\">",
                h(&result.case_id),
                uri
            )
        })
        .unwrap_or_else(|| "<div class=\"muted\">No screenshot captured.</div>".to_owned());
    Ok(format!(
        "<article class=\"case\"><div><h3>{}</h3><dl class=\"facts\"><dt>Classification</dt><dd><span class=\"status {}\">{:?}</span></dd><dt>Expected</dt><dd>{}</dd><dt>Actual</dt><dd>{}</dd><dt>Starting state</dt><dd><code>{:?} / {:?} / {:?} / {:?}</code></dd><dt>Failure class</dt><dd>{}</dd><dt>Replay</dt><dd><code>{}</code></dd><dt>Evidence complete</dt><dd>{}</dd></dl><details><summary>Relevant device logs</summary><pre>{}</pre></details></div><div>{}</div></article>",
        h(&result.case_id), status_class(result.classification), result.classification,
        destination(&result.expected), destination(&result.actual), result.starting_state.install,
        result.starting_state.launch, result.starting_state.verification, result.starting_state.user_default,
        h(result.runtime_failure_class.as_deref().unwrap_or("—")), h(&result.replay),
        if result.evidence.complete_for_failure { "yes" } else { "no" }, h(&logs), image
    ))
}

fn destination(value: &crate::model::ObservedDestination) -> String {
    match &value.destination {
        Some(destination) => format!("<code>{} · {}</code>", h(&value.target), h(destination)),
        None => format!("<code>{}</code>", h(&value.target)),
    }
}

fn status_class(classification: Classification) -> &'static str {
    if classification == Classification::Passed {
        "passed"
    } else if classification.is_unavailable() {
        "unavailable"
    } else {
        "failed"
    }
}

fn h(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn escape_script(value: &str) -> String {
    value
        .replace('<', "\\u003c")
        .replace('>', "\\u003e")
        .replace('&', "\\u0026")
}

#[cfg(test)]
mod tests {
    use chrono::Utc;
    use tempfile::tempdir;

    use super::*;
    use crate::model::*;

    #[test]
    fn report_is_portable_and_explicit_about_simulation() {
        let dir = tempdir().unwrap();
        let report = RunReport {
            schema_version: 1,
            tool_version: "0.1.0".into(),
            run_id: "test".into(),
            generated_at: Utc::now(),
            spec: "deeplinklab.yml".into(),
            reference_setup: None,
            preflight: PreflightReport {
                schema_version: 1,
                spec_version: 1,
                valid: true,
                errors: 0,
                warnings: 0,
                issues: vec![],
            },
            summary: RunSummary::default(),
            results: vec![],
        };
        let html = render_html(&report, dir.path()).unwrap();
        assert!(html.contains("<!doctype html>"));
        assert!(html.contains("not real-device proof"));
        assert!(!html.contains("https://fonts"));
    }
}
